import os

import numpy as np
import pandas as pd
import timm
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score, classification_report
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from tqdm import tqdm


# --- 1. Define Model Architecture (Must match training) ---
class Classifier(nn.Module):
    def __init__(self, model_name="resnet18", num_classes=10, in_chans=1):
        super(Classifier, self).__init__()
        self.base_model = timm.create_model(
            model_name,
            pretrained=False,  # No need to download pretrained weights again, we load ours
            num_classes=num_classes,
            in_chans=in_chans,
        )

    def forward(self, x):
        return self.base_model(x)


# --- Configuration ---
# Update this path to point to the .pth file generated by your training script
# Example: "outputs_MNIST/16_Feb_resnet18/classifier_limited_data_best_auc.pth"
model_path = "outputs_MNIST/16_Feb_resnet18/distinctive-snowball-1_28_best_auc.pth"
file_path = "MNIST_validation_results.xlsx"
model_name_arch = "resnet18"
num_classes = 10
IMG_SIZE = 32

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# --- 2. Load Model ---
# Initialize the model structure
model = Classifier(model_name=model_name_arch, num_classes=num_classes, in_chans=1)
model.to(device)

# Load the trained weights
if os.path.exists(model_path):
    print(f"Loading weights from {model_path}...")
    state_dict = torch.load(model_path, map_location=device)
    model.load_state_dict(state_dict)
else:
    print(
        f"WARNING: Model path {model_path} not found. Using random weights for testing."
    )

model.eval()

# --- 3. Load Data ---
transform = transforms.Compose(
    [
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize((0.5,), (0.5,)),
    ]
)

val_dataset = datasets.MNIST(
    "./data",  # Use local path
    train=False,
    download=True,
    transform=transform,
)
test_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)

# --- 4. Inference ---
predicted_labels = []
actual_labels = []

print("Running inference...")
with torch.no_grad():
    for images, labels in tqdm(test_loader):
        images = images.to(device)

        # Get raw logits
        outputs = model(images)
        # Get predictions
        _, preds = torch.max(outputs, 1)

        predicted_labels.extend(preds.cpu().numpy())
        actual_labels.extend(labels.cpu().numpy())

predicted_labels = np.array(predicted_labels)
actual_labels = np.array(actual_labels)

# --- 5. Metrics & Reporting ---
# Generate a dictionary report
report = classification_report(
    actual_labels, predicted_labels, output_dict=True, zero_division=0
)

# Extract Overall Accuracy
overall_acc = accuracy_score(actual_labels, predicted_labels)

# Build the Data Dictionary
data_dict = {
    "Model Name": model_name_arch,
    "Model Path": model_path,
    "Overall Accuracy": overall_acc,
    "------": "",  # Visual separator
}

# Loop through classes 0-9 to get per-class accuracy (Recall)
# Recall is used here because "Accuracy for Class X" usually means
# "How many of the actual X's did we correctly label as X?"
for i in range(num_classes):
    class_name = str(i)
    if class_name in report:
        metric = report[class_name]["recall"]  # Recall = Class Accuracy
        data_dict[f"Class {i} Accuracy"] = metric

# Create DataFrame
col_name = os.path.basename(model_path)  # Use filename as column header
new_column = pd.Series(data_dict, name=col_name)
new_df = new_column.to_frame()

print("\n--- Results ---")
print(new_df)

# --- 6. Save to Excel ---
print(f"\nSaving to {file_path}...")

if os.path.exists(file_path):
    try:
        existing_data = pd.read_excel(file_path, index_col=0)
        # Combine old data with new column
        combined_data = pd.concat([existing_data, new_df], axis=1)
        combined_data.to_excel(file_path)
    except Exception as e:
        print(f"Error reading existing excel: {e}. Saving new file.")
        new_df.to_excel(file_path)
else:
    new_df.to_excel(file_path)

print("Done.")
